Made bin/sea more picky about where it finds bin/narwhal.

diff --git a/bin/sea b/bin/sea
--- a/bin/sea
+++ b/bin/sea
@@ -16,14 +16,16 @@ done
 PACKAGE_HOME=$(dirname -- "$(dirname -- "$SELF_PATH")")
 
 # which -s narwhal doesn't work (os x 10.5, kriskowal)
-env narwhal -e '' >/dev/null 2>&1
-if [ "$?" -ne 127 ]; then
-    NARWHAL=narwhal
-elif [ -f "$PACKAGE_HOME"/bin/narwhal ]; then
+if [ -f "$PACKAGE_HOME"/bin/narwhal ]; then
     NARWHAL="$PACKAGE_HOME"/bin/narwhal
 else
-    echo "ERROR: narwhal is not in your PATH or $PACKAGE_HOME/bin."
-    exit
+    env narwhal -e '' >/dev/null 2>&1
+    if [ "$?" -ne 127 ]; then
+        NARWHAL=narwhal
+    else
+        echo "ERROR: narwhal is not in your PATH or $PACKAGE_HOME/bin."
+        exit
+    fi
 fi
 
 if [ -f "$PACKAGE_HOME"/narwhal.conf ]; then
