Fixed a bug in bin/sea caused by 'which -s' failing to report the existence of 'narwhal' on the PATH.  Used env and checked the exit code instead.

diff --git a/bin/sea b/bin/sea
--- a/bin/sea
+++ b/bin/sea
@@ -10,22 +10,33 @@ SELF_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELF_PATH=$SELF_PATH/$(b
 while [ -h "$SELF_PATH" ]; do
 	DIR=$(dirname -- "$SELF_PATH")
 	SYM=$(readlink -- "$SELF_PATH")
-	SELF_PATH=$(cd "$DIR" && cd $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
+	SELF_PATH=$(cd -- "$DIR" && cd -- $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
 done
 
 PACKAGE_HOME=$(dirname -- "$(dirname -- "$SELF_PATH")")
 
-if which -s narwhal >/dev/null; then
+# which -s narwhal doesn't work (os x 10.5, kriskowal)
+env narwhal -e '' >/dev/null 2>&1
+if [ "$?" -ne 127 ]; then
+    NARWHAL=narwhal
+elif [ -f "$PACKAGE_HOME"/bin/narwhal ]; then
     NARWHAL="$PACKAGE_HOME"/bin/narwhal
 else
-    NARWHAL=narwhal
+    echo "ERROR: narwhal is not in your PATH or $PACKAGE_HOME/bin."
+    exit
 fi
 
-export PATH=$("$NARWHAL" --package  "$PACKAGE_HOME" --path :) 
+if [ -f "$PACKAGE_HOME"/narwhal.conf ]; then
+    source "$PACKAGE_HOME"/narwhal.conf
+    export NARWHAL_DEFAULT_PLATFORM
+fi
+
+export PATH="$("$NARWHAL" --package  "$PACKAGE_HOME" --path :)"
 export SEA_LEVEL="$((SEA_LEVEL + 1))" 
 
-if [ $# -lt 1 ]; then
+if [ "$#" -lt 1 ]; then
     echo PATH="$PATH" >&2
+    echo SEA_LEVEL="$SEA_LEVEL" >&2
     "$SHELL"
 else
     "$SHELL" -c "$*"
